services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./scripts/pg_multiple_dbs.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/postgres.env

  memcached:
    image: memcached:latest
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    ports:
      - 11211:11211
    restart: always

volumes:
  postgres_data: