services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./scripts/pg_multiple_dbs.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/postgres.env

volumes:
  postgres_data: