package response

// DocsErrorResponse represents an example error response for Swagger documentation.
// It includes a message that describes the error and a set of validation errors
// related to specific fields. This struct is used to provide example error responses
// in API documentation generated by Swagger.
type DocsErrorResponse struct {
	Message string `json:"message" example:"Invalid request body"`
	Errors  struct {
		FieldName string `json:"fieldName" example:"error message"`
	} `json:"errors"`
}

// DocsErrorResponseInternalServerErr represents an example internal server error response
// for Swagger documentation. It includes a message describing the internal server error.
// This struct is used to provide example internal server error responses in API documentation
// generated by Swagger.
type DocsErrorResponseInternalServerErr struct {
	Message string `json:"message" example:"internal server error"`
}

// DocsSuccessResponseLoginUser represents an example success response for a user login
// in Swagger documentation. It includes a token that would typically be returned upon
// successful authentication. This struct is used to provide example success responses
// in API documentation generated by Swagger, specifically for the login process.
type DocsSuccessResponseLoginUser struct {
	Data struct {
		Token string `json:"token" example:"jwt.access.token"`
	} `json:"data"`
}

// DocsSuccessResponseRegisterUser represents an example success response for user registration
// in Swagger documentation. It includes a message indicating the success of the registration process.
// This struct is used to provide example success responses in API documentation generated by Swagger,
// specifically for user registration.
type DocsSuccessResponseRegisterUser struct {
	Message string `json:"message" example:"Done."`
}
